name: nm
version: 0.5.0

description:
  Provides a client to connect to NetworkManager - the service that manages network connections on Linux.
publish_to: none
homepage: https://github.com/canonical/nm.dart

environment:
  sdk: '>=3.12.0 <4.0.0'

platforms:
  linux:

dependencies:
  dbus:
    git: https://github.com/kumsumit/dbus.dart.git

dev_dependencies:
  lints: ^6.1.0
  test: ^1.31.1
  test_cov: ^1.0.1

